# ~/.config/lazygit/config.yml

gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "green"
      - "bold"
    inactiveBorderColor:
      - "white"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

